"""Conservative C register-header importer.

The importer never invokes a C preprocessor and never executes macro text.  It
recognizes the portable integer-macro conventions generated by most register
tools and evaluates only a bounded, side-effect-free integer expression subset.
"""

from __future__ import annotations

import ast
import re
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from opencollate.diagnostics import Diagnostic, Severity
from opencollate.model import (
    FactState,
    RegisterFieldObservation,
    RegisterObservation,
    ViewId,
    ViewObservation,
)
from opencollate.parsers.base import (
    Pathish,
    coerce_paths,
    coerce_view,
    parser_diagnostic,
    provenance,
    read_source,
)

_DEFINE_RE = re.compile(r"^\s*#\s*define\s+([A-Za-z_]\w*)\s+(.+?)\s*$")
_DEFINE_DIRECTIVE_RE = re.compile(r"^\s*#\s*define\s+([A-Za-z_]\w*)\b")
_CONDITIONAL_RE = re.compile(
    r"^\s*#\s*(if|ifdef|ifndef|elif|else|endif)\b(?:\s+(.*?))?\s*$",
    re.IGNORECASE,
)
_PRAGMA_ONCE_RE = re.compile(r"^\s*#\s*pragma\s+once\b", re.IGNORECASE)
_IDENTIFIER_RE = re.compile(r"\b[A-Za-z_]\w*\b")
_INTEGER_SUFFIX_RE = re.compile(r"(?i)\b(0[x][0-9a-f]+|0[b][01]+|0[0-7]+|[1-9][0-9]*|0)(?:u|l)+\b")
_CAST_RE = re.compile(
    r"(?ix)\(\s*(?:const\s+|volatile\s+|signed\s+|unsigned\s+)*"
    r"(?:u?int(?:8|16|32|64)_t|char|short|int|long)(?:\s+int)?\s*\)"
)
_BASE_SUFFIXES = ("_BASE_ADDRESS", "_BASE_ADDR", "_BASE")
_ADDRESS_SUFFIXES = ("_ADDRESS", "_ADDR")
_OFFSET_SUFFIXES = ("_REGISTER_OFFSET", "_REG_OFFSET", "_OFFSET")
_FIELD_SUFFIXES = {
    "_POSITION": "position",
    "_POS": "position",
    "_LSB": "position",
    "_MASK": "mask",
    "_MSK": "mask",
    "_WIDTH": "width",
    "_RESET_VALUE": "reset",
    "_RESETVALUE": "reset",
    "_RESET": "reset",
}
_MAX_EXPRESSION_CHARS = 4096
_MAX_AST_NODES = 512
_MAX_MACRO_DEPTH = 64
_MAX_INTEGER_BITS = 4096
_MAX_SOURCE_CHARACTERS = 16 * 1024 * 1024
_MAX_MACROS = 200_000


@dataclass(frozen=True, slots=True)
class _Macro:
    name: str
    expression: str
    path: Path
    line: int
    conditional: bool = False


def _fact_rank(fact: tuple[int, _Macro]) -> tuple[str, str, int, int]:
    value, macro = fact
    return macro.name, macro.path.as_posix(), macro.line, value


class _IntegerExpressionError(ValueError):
    pass


class _IntegerEvaluator:
    def __init__(self, macros: Mapping[str, _Macro]) -> None:
        self.macros = macros
        self.cache: dict[str, int] = {}
        self.active: list[str] = []

    def macro(self, name: str) -> int:
        if name in self.cache:
            return self.cache[name]
        macro = self.macros.get(name)
        if macro is None:
            raise _IntegerExpressionError(f"unknown macro {name}")
        if name in self.active:
            cycle = " -> ".join((*self.active, name))
            raise _IntegerExpressionError(f"cyclic macro expansion: {cycle}")
        if len(self.active) >= _MAX_MACRO_DEPTH:
            raise _IntegerExpressionError("macro expansion exceeds 64 levels")
        self.active.append(name)
        try:
            value = self.expression(macro.expression)
        finally:
            self.active.pop()
        self.cache[name] = value
        return value

    def expression(self, expression: str) -> int:
        if len(expression) > _MAX_EXPRESSION_CHARS:
            raise _IntegerExpressionError("integer expression exceeds 4096 characters")
        normalized = _CAST_RE.sub("", expression.strip())
        normalized = _INTEGER_SUFFIX_RE.sub(lambda match: match.group(1), normalized)
        normalized = re.sub(r"\b0([0-7]+)\b", r"0o\1", normalized)
        try:
            tree = ast.parse(normalized, mode="eval")
        except (SyntaxError, ValueError) as error:
            raise _IntegerExpressionError("not a supported integer expression") from error
        if sum(1 for _ in ast.walk(tree)) > _MAX_AST_NODES:
            raise _IntegerExpressionError("integer expression exceeds 512 syntax nodes")
        return self._node(tree.body)

    def _node(self, node: ast.AST) -> int:
        if isinstance(node, ast.Constant) and type(node.value) is int:
            return self._bounded(node.value)
        if isinstance(node, ast.Name):
            return self.macro(node.id)
        if isinstance(node, ast.UnaryOp):
            value = self._node(node.operand)
            if isinstance(node.op, ast.UAdd):
                return value
            if isinstance(node.op, ast.USub):
                return self._bounded(-value)
            if isinstance(node.op, ast.Invert):
                return self._bounded(~value)
        if isinstance(node, ast.BinOp):
            left = self._node(node.left)
            right = self._node(node.right)
            if isinstance(node.op, ast.Add):
                return self._bounded(left + right)
            if isinstance(node.op, ast.Sub):
                return self._bounded(left - right)
            if isinstance(node.op, ast.Mult):
                return self._bounded(left * right)
            if isinstance(node.op, (ast.Div, ast.FloorDiv)):
                if right == 0:
                    raise _IntegerExpressionError("division by zero")
                quotient = abs(left) // abs(right)
                return -quotient if (left < 0) != (right < 0) else quotient
            if isinstance(node.op, ast.Mod):
                if right == 0:
                    raise _IntegerExpressionError("division by zero")
                return left % right
            if isinstance(node.op, ast.LShift):
                if right < 0 or right > _MAX_INTEGER_BITS:
                    raise _IntegerExpressionError("shift count is outside the supported range")
                return self._bounded(left << right)
            if isinstance(node.op, ast.RShift):
                if right < 0 or right > _MAX_INTEGER_BITS:
                    raise _IntegerExpressionError("shift count is outside the supported range")
                return left >> right
            if isinstance(node.op, ast.BitAnd):
                return self._bounded(left & right)
            if isinstance(node.op, ast.BitOr):
                return self._bounded(left | right)
            if isinstance(node.op, ast.BitXor):
                return self._bounded(left ^ right)
        raise _IntegerExpressionError(f"unsupported integer operator {type(node).__name__}")

    @staticmethod
    def _bounded(value: int) -> int:
        if value.bit_length() > _MAX_INTEGER_BITS:
            raise _IntegerExpressionError("integer result exceeds 4096 bits")
        return value


def _logical_lines(text: str) -> Iterable[tuple[int, str]]:
    """Join backslash continuations while retaining the first physical line."""

    pending = ""
    start = 1
    in_block_comment = False
    for number, raw in enumerate(text.splitlines(), 1):
        clean: list[str] = []
        index = 0
        while index < len(raw):
            if in_block_comment:
                end = raw.find("*/", index)
                if end < 0:
                    index = len(raw)
                    continue
                in_block_comment = False
                index = end + 2
                continue
            block = raw.find("/*", index)
            line = raw.find("//", index)
            if line >= 0 and (block < 0 or line < block):
                clean.append(raw[index:line])
                index = len(raw)
                continue
            if block >= 0:
                clean.append(raw[index:block])
                in_block_comment = True
                index = block + 2
                continue
            clean.append(raw[index:])
            index = len(raw)
        fragment = "".join(clean).rstrip()
        if not pending:
            start = number
        if fragment.endswith("\\"):
            pending += fragment[:-1] + " "
            continue
        yield start, pending + fragment
        pending = ""
    if pending:
        yield start, pending


def _include_guard_name(lines: Sequence[tuple[int, str]]) -> str | None:
    """Recognize only a conventional outer ``#ifndef`` include guard."""

    meaningful = [item for item in lines if item[1].strip()]
    while meaningful and _PRAGMA_ONCE_RE.match(meaningful[0][1]):
        meaningful.pop(0)
    if len(meaningful) < 3:
        return None
    opening = _CONDITIONAL_RE.match(meaningful[0][1])
    guard_define = _DEFINE_DIRECTIVE_RE.match(meaningful[1][1])
    closing = _CONDITIONAL_RE.match(meaningful[-1][1])
    if (
        opening is None
        or opening.group(1).casefold() != "ifndef"
        or guard_define is None
        or closing is None
        or closing.group(1).casefold() != "endif"
    ):
        return None
    guard = (opening.group(2) or "").strip()
    if not re.fullmatch(r"[A-Za-z_]\w*", guard) or guard_define.group(1) != guard:
        return None
    depth = 0
    for index, (_, text) in enumerate(meaningful):
        directive = _CONDITIONAL_RE.match(text)
        if directive is None:
            continue
        command = directive.group(1).casefold()
        if command in {"if", "ifdef", "ifndef"}:
            depth += 1
        elif command in {"elif", "else"} and depth == 1:
            return None
        elif command == "endif":
            depth -= 1
            if depth == 0 and index != len(meaningful) - 1:
                return None
            if depth < 0:
                return None
    return guard if depth == 0 else None


def _conditionally_derived_macros(
    macros: Mapping[str, _Macro],
    directly_conditional: set[str],
) -> set[str]:
    """Find macros whose value transitively depends on a conditional definition."""

    cache: dict[str, bool] = {}

    def visit(name: str, active: frozenset[str]) -> bool:
        if name in directly_conditional:
            return True
        if name in cache:
            return cache[name]
        if name in active or len(active) >= _MAX_MACRO_DEPTH:
            return True
        macro = macros.get(name)
        if macro is None:
            return False
        dependencies = {item for item in _IDENTIFIER_RE.findall(macro.expression) if item in macros}
        result = any(visit(item, active | {name}) for item in dependencies)
        cache[name] = result
        return result

    return {name for name in macros if visit(name, frozenset())}


def _prefix_for(name: str, prefixes: Sequence[str]) -> str:
    matches = [prefix for prefix in prefixes if name.startswith(prefix + "_")]
    if matches:
        return max(matches, key=len)
    return name.split("_", 1)[0]


def _strip_suffix(name: str, suffixes: Sequence[str]) -> tuple[str, str] | None:
    for suffix in suffixes:
        if name.endswith(suffix) and len(name) > len(suffix):
            return name[: -len(suffix)], suffix
    return None


def _field_facts(
    *,
    stem: str,
    register_stem: str,
    evaluator: _IntegerEvaluator,
    macros: Mapping[str, _Macro],
    view: ViewId,
    diagnostics: list[Diagnostic],
    conditional_macros: set[str],
) -> tuple[RegisterFieldObservation, ...]:
    values: dict[str, dict[str, tuple[int, _Macro]]] = {}
    conflicts: set[str] = set()
    prefix = register_stem + "_"
    for name, macro in macros.items():
        if not name.startswith(prefix):
            continue
        tail = name[len(prefix) :]
        tail_upper = tail.upper()
        matched = next(
            (
                (suffix, fact)
                for suffix, fact in _FIELD_SUFFIXES.items()
                if tail_upper.endswith(suffix)
            ),
            None,
        )
        if matched is None:
            continue
        suffix, fact = matched
        field_name = tail[: -len(suffix)]
        if not field_name:
            continue
        try:
            value = evaluator.macro(name)
        except _IntegerExpressionError as error:
            diagnostics.append(
                parser_diagnostic(
                    "OC1103",
                    Severity.WARNING,
                    f"Cannot resolve register macro {name}: {error}",
                    location=provenance(macro.path, view, line=macro.line, raw_name=name),
                )
            )
            continue
        field_values = values.setdefault(field_name, {})
        if name in conditional_macros:
            conflicts.add(field_name)
        candidate = (value, macro)
        previous = field_values.get(fact)
        if previous is not None and previous[0] != value:
            diagnostics.append(
                parser_diagnostic(
                    "OC1102",
                    Severity.WARNING,
                    f"C header field macros {previous[1].name} and {name} disagree",
                    location=provenance(macro.path, view, line=macro.line, raw_name=name),
                    help="Select one generated register-header convention or build configuration.",
                )
            )
            conflicts.add(field_name)
        field_values[fact] = min(
            (candidate, previous) if previous is not None else (candidate,),
            key=_fact_rank,
        )

    fields: list[RegisterFieldObservation] = []
    for field_name, facts in sorted(values.items()):
        position = facts.get("position", (None, None))[0]
        width = facts.get("width", (None, None))[0]
        mask = facts.get("mask", (None, None))[0]
        state = FactState.TAINTED if field_name in conflicts else FactState.KNOWN
        detail: dict[str, Any] = {"macro_stem": stem}
        if field_name in conflicts:
            detail["conflicting_macros"] = True
        if position is not None and position < 0:
            detail["invalid_position"] = position
            position = None
            state = FactState.TAINTED
        if width is not None and width < 1:
            detail["invalid_width"] = width
            width = None
            state = FactState.TAINTED
        if mask is not None:
            if mask < 0:
                state = FactState.TAINTED
            else:
                inferred_position = (mask & -mask).bit_length() - 1 if mask else 0
                position = inferred_position if position is None else position
                shifted = mask >> position if position is not None else mask
                inferred_width = shifted.bit_length()
                if shifted and shifted == (1 << inferred_width) - 1:
                    width = inferred_width if width is None else width
                else:
                    state = FactState.TAINTED
                    detail["noncontiguous_mask"] = mask
        evidence_macro = next((item[1] for item in facts.values() if item[1] is not None), None)
        fields.append(
            RegisterFieldObservation(
                native_name=field_name,
                bit_offset=position,
                bit_width=width,
                reset_value=facts.get("reset", (None, None))[0],
                provenance=(
                    provenance(
                        evidence_macro.path,
                        view,
                        line=evidence_macro.line,
                        raw_name=evidence_macro.name,
                    )
                    if evidence_macro is not None
                    else None
                ),
                status=state,
                attributes=detail,
            )
        )
    return tuple(fields)


def parse_c_header(
    paths: Pathish | Sequence[Pathish],
    *,
    view_id: ViewId | str | None = None,
    view_name: str = "default",
    component_name: str | None = None,
    macro_prefix: str | None = None,
    default_register_width: int | None = None,
) -> ViewObservation:
    """Import conventional ``*_OFFSET``, ``*_ADDR``, and field macros."""

    source_paths = tuple(
        sorted(
            coerce_paths(paths),
            key=lambda path: (path.as_posix().casefold(), path.as_posix()),
        )
    )
    view = coerce_view(view_id, kind="header", name=view_name)
    if default_register_width is not None and (
        type(default_register_width) is not int or default_register_width < 1
    ):
        raise ValueError("default_register_width must be a positive integer")
    macros: dict[str, _Macro] = {}
    diagnostics: list[Diagnostic] = []
    complete = True
    tainted: set[str] = set()
    directly_conditional: set[str] = set()
    conditional_occurrences: dict[Path, list[_Macro]] = {}
    for path in source_paths:
        source = read_source(path, view)
        diagnostics.extend(source.diagnostics)
        complete &= not source.tainted
        if source.tainted:
            tainted.add("*")
        if len(source.text) > _MAX_SOURCE_CHARACTERS:
            diagnostics.append(
                parser_diagnostic(
                    "OC1101",
                    Severity.FATAL,
                    f"C header {path} exceeds the 16 MiB parser limit",
                    location=provenance(path, view),
                )
            )
            complete = False
            tainted.add("*")
            continue
        logical_lines = tuple(_logical_lines(source.text))
        include_guard = _include_guard_name(logical_lines)
        conditional_stack: list[bool] = []
        file_macro_names: set[str] = set()
        conditional_structure_invalid = False
        structure_diagnostic_emitted = False
        for line, text in logical_lines:
            directive = _CONDITIONAL_RE.match(text)
            if directive is not None:
                command = directive.group(1).casefold()
                argument = (directive.group(2) or "").strip()
                if command in {"if", "ifdef", "ifndef"}:
                    is_include_guard = (
                        not conditional_stack
                        and command == "ifndef"
                        and include_guard is not None
                        and argument == include_guard
                    )
                    conditional_stack.append(is_include_guard)
                elif command in {"elif", "else"}:
                    if not conditional_stack:
                        conditional_structure_invalid = True
                elif conditional_stack:
                    conditional_stack.pop()
                else:
                    conditional_structure_invalid = True
                if conditional_structure_invalid and not structure_diagnostic_emitted:
                    diagnostics.append(
                        parser_diagnostic(
                            "OC1102",
                            Severity.WARNING,
                            "C header has an unbalanced conditional preprocessing directive",
                            location=provenance(path, view, line=line),
                            help="Preprocess the selected build configuration before importing it.",
                        )
                    )
                    structure_diagnostic_emitted = True
                continue
            match = _DEFINE_RE.match(text)
            if match is None:
                continue
            name, expression = match.groups()
            conditional = conditional_structure_invalid or any(
                not is_include_guard for is_include_guard in conditional_stack
            )
            macro = _Macro(name, expression.strip(), path, line, conditional)
            file_macro_names.add(name)
            if conditional:
                directly_conditional.add(name)
                conditional_occurrences.setdefault(path, []).append(macro)
            previous = macros.get(name)
            if previous is not None and previous.expression != macro.expression:
                diagnostics.append(
                    parser_diagnostic(
                        "OC1102",
                        Severity.WARNING,
                        f"C header macro {name} has conditional or conflicting definitions",
                        location=provenance(path, view, line=line, raw_name=name),
                        help="Preprocess the selected build configuration before importing it.",
                    )
                )
                tainted.add(name)
            if name not in macros and len(macros) >= _MAX_MACROS:
                diagnostics.append(
                    parser_diagnostic(
                        "OC1101",
                        Severity.FATAL,
                        f"C header view exceeds the {_MAX_MACROS:,} macro limit",
                        location=provenance(path, view, line=line),
                    )
                )
                complete = False
                tainted.add("*")
                break
            macros[name] = min(
                (previous, macro) if previous is not None else (macro,),
                key=lambda item: (
                    item.expression,
                    item.path.as_posix(),
                    item.line,
                ),
            )
        if conditional_stack:
            conditional_structure_invalid = True
            if not structure_diagnostic_emitted:
                diagnostics.append(
                    parser_diagnostic(
                        "OC1102",
                        Severity.WARNING,
                        "C header has an unterminated conditional preprocessing block",
                        location=provenance(path, view),
                        help="Preprocess the selected build configuration before importing it.",
                    )
                )
        if conditional_structure_invalid:
            directly_conditional.update(file_macro_names)
            complete = False
            tainted.add("*")

    conditional_macros = _conditionally_derived_macros(macros, directly_conditional)
    tainted.update(conditional_macros)
    for path, occurrences in sorted(
        conditional_occurrences.items(), key=lambda item: item[0].as_posix()
    ):
        first = min(occurrences, key=lambda item: item.line)
        diagnostics.append(
            parser_diagnostic(
                "OC1104",
                Severity.WARNING,
                f"C header contains {len(occurrences)} macro definition(s) behind "
                "unresolved preprocessing conditions; dependent facts are tainted",
                location=provenance(
                    path,
                    view,
                    line=first.line,
                    raw_name=first.name,
                ),
                help="Preprocess the selected build configuration for known register facts.",
            )
        )

    evaluator = _IntegerEvaluator(macros)
    base_macros: dict[str, tuple[int, _Macro]] = {}
    base_conflicts: set[str] = set()
    for name, macro in macros.items():
        stripped = _strip_suffix(name, _BASE_SUFFIXES)
        if stripped is None:
            continue
        prefix, _ = stripped
        try:
            candidate = (evaluator.macro(name), macro)
            if name in conditional_macros:
                tainted.add(prefix)
            previous_base = base_macros.get(prefix)
            if previous_base is not None and previous_base[0] != candidate[0]:
                diagnostics.append(
                    parser_diagnostic(
                        "OC1102",
                        Severity.WARNING,
                        f"C header base-address macros {previous_base[1].name} and {name} disagree",
                        location=provenance(macro.path, view, line=macro.line, raw_name=name),
                        help=(
                            "Select one generated register-header convention or build "
                            "configuration."
                        ),
                    )
                )
                base_conflicts.add(prefix)
                tainted.add(prefix)
            base_macros[prefix] = min(
                (candidate, previous_base) if previous_base is not None else (candidate,),
                key=_fact_rank,
            )
        except _IntegerExpressionError as error:
            diagnostics.append(
                parser_diagnostic(
                    "OC1103",
                    Severity.WARNING,
                    f"Cannot resolve base-address macro {name}: {error}",
                    location=provenance(macro.path, view, line=macro.line, raw_name=name),
                )
            )

    configured_prefixes = [macro_prefix] if macro_prefix else sorted(base_macros, key=len)
    register_macros: dict[tuple[str, str], dict[str, tuple[int, _Macro]]] = {}
    for name, macro in macros.items():
        suffix_match = _strip_suffix(name, _OFFSET_SUFFIXES)
        kind = "offset"
        if suffix_match is None:
            suffix_match = _strip_suffix(name, _ADDRESS_SUFFIXES)
            kind = "address"
        if suffix_match is None:
            continue
        stem, _ = suffix_match
        prefix = _prefix_for(stem, configured_prefixes)
        if macro_prefix is not None and prefix != macro_prefix:
            continue
        register_name = stem[len(prefix) :].lstrip("_")
        if register_name.endswith("_REG"):
            register_name = register_name[:-4]
        if not register_name or register_name in {"BASE", "BASE_ADDR", "BASE_ADDRESS"}:
            continue
        try:
            value = evaluator.macro(name)
        except _IntegerExpressionError as error:
            diagnostics.append(
                parser_diagnostic(
                    "OC1103",
                    Severity.WARNING,
                    f"Cannot resolve register macro {name}: {error}",
                    location=provenance(macro.path, view, line=macro.line, raw_name=name),
                )
            )
            tainted.add(f"{prefix}/{register_name}")
            continue
        if name in conditional_macros:
            tainted.add(f"{prefix}/{register_name}")
        register_facts = register_macros.setdefault((prefix, register_name), {})
        candidate = (value, macro)
        previous_fact = register_facts.get(kind)
        if previous_fact is not None and previous_fact[0] != value:
            diagnostics.append(
                parser_diagnostic(
                    "OC1102",
                    Severity.WARNING,
                    f"C header register macros {previous_fact[1].name} and {name} disagree",
                    location=provenance(macro.path, view, line=macro.line, raw_name=name),
                    help="Select one generated register-header convention or build configuration.",
                )
            )
            tainted.add(f"{prefix}/{register_name}")
        register_facts[kind] = min(
            (candidate, previous_fact) if previous_fact is not None else (candidate,),
            key=_fact_rank,
        )

    registers: list[RegisterObservation] = []
    for (prefix, register_name), facts in sorted(register_macros.items()):
        offset = facts.get("offset", (None, None))[0]
        address = facts.get("address", (None, None))[0]
        base = base_macros.get(prefix, (None, None))[0]
        if address is not None and base is not None and address >= base and offset is None:
            offset = address - base
        if address is None and base is not None and offset is not None:
            address = base + offset
        if (
            address is not None
            and base is not None
            and offset is not None
            and address != base + offset
        ):
            diagnostics.append(
                parser_diagnostic(
                    "OC1101",
                    Severity.FATAL,
                    f"{prefix}/{register_name} address and offset macros disagree",
                    location=provenance(
                        facts["address"][1].path,
                        view,
                        line=facts["address"][1].line,
                        raw_name=facts["address"][1].name,
                    ),
                )
            )
            tainted.add(f"{prefix}/{register_name}")
        offset_fact = facts.get("offset")
        address_fact = facts.get("address")
        evidence_fact = offset_fact or address_fact
        if evidence_fact is None:  # defensive: discovery adds only these two fact kinds
            continue
        evidence = evidence_fact[1]
        register_stem = f"{prefix}_{register_name}"
        register_scope = f"{prefix}/{register_name}"
        register_tainted = (
            "*" in tainted
            or prefix in base_conflicts
            or prefix in tainted
            or register_scope in tainted
            or any(macro.name in tainted for _, macro in facts.values())
        )
        fields = _field_facts(
            stem=register_stem,
            register_stem=register_stem,
            evaluator=evaluator,
            macros=macros,
            view=view,
            diagnostics=diagnostics,
            conditional_macros=conditional_macros,
        )
        register_tainted = register_tainted or any(
            field.status != FactState.KNOWN for field in fields
        )
        if register_tainted:
            tainted.add(register_scope)
        registers.append(
            RegisterObservation(
                native_name=register_name,
                component=component_name or prefix,
                memory_map=prefix,
                address_offset=offset,
                absolute_address=address,
                size_bits=default_register_width,
                fields=fields,
                provenance=provenance(
                    evidence.path,
                    view,
                    line=evidence.line,
                    raw_name=evidence.name,
                ),
                status=(FactState.TAINTED if register_tainted else FactState.KNOWN),
                attributes={
                    "macro_prefix": prefix,
                    "base_address": base,
                    "address_macro": address_fact[1].name if address_fact else None,
                    "offset_macro": offset_fact[1].name if offset_fact else None,
                },
            )
        )

    if macros and not registers:
        diagnostics.append(
            parser_diagnostic(
                "OC1105",
                Severity.INFO,
                "No supported register address or offset macros were found in the C header view",
                location=provenance(source_paths[0], view),
                help="Use *_OFFSET or *_ADDR macros, or configure macro_prefix.",
            )
        )
    return ViewObservation(
        view=view,
        diagnostics=tuple(diagnostics),
        complete=complete,
        tainted_scopes=frozenset(tainted),
        registers=tuple(registers),
        attributes={
            "parser": "c-header",
            "source_files": [str(path) for path in source_paths],
            "macro_count": len(macros),
            "component_name": component_name,
            "macro_prefix": macro_prefix,
        },
    )


class CHeaderParser:
    format_name = "header"

    def parse(
        self,
        paths: Sequence[Pathish],
        *,
        view_id: ViewId | str | None = None,
        **options: Any,
    ) -> ViewObservation:
        return parse_c_header(paths, view_id=view_id, **options)


__all__ = ["CHeaderParser", "parse_c_header"]
